Revert "Fix NoClassDefFoundError in SmartGadgetManager"
This reverts commit 27aa27ccd6125708b6d86f70574fe5ccbd353140.

Change-Id: I4ae335dbfda683fff713eef84735cd94f6e303b1